src/__test__/fixtures/basic.input.js
src/__test__/fixtures/basic.output.js
src/convertToPropTypes.js
src/makePropTypesAst.js

So, this is a bit of a wildcard.
I've found it useful in some libraries I use to actually error out when a user provides a property I don't want them to set - perhaps as a way of deprecating props, or to discourage bad behavior.
I considered having it transform to `oneOf([null, undefined])`, but the error message is unclear:
> Warning: Failed propType: Invalid prop `foo` of value `bar` supplied to `Child`, expected one of [null,null]. Check the render method of `Parent`.
This function warns:
>Warning: Failed propType: Invalid prop `foo` of value `bar` passed to `Child`. Expected void. Check the render method of `Parent`.
See http://astexplorer.net/#/zZKFxnO2nA/2 for an example in action.

Add void support.

---

package.json
src/__test__/fixtures/function-types.input.js

Two straightforward bug fixes.
```
$ git clone https://github.com/brigand/babel-plugin-flow-react-proptypes
$ cd babel-plugin-flow-react-proptypes
$ npm install && npm test
```
Currently yields a whole bunch of:
```
Prop types for src/__test__/fixtures/function-types.output.js:
Error: Cannot find module 'babel-template'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:286:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (/Users/marcus.armstrong/babel-plugin-flow-react-proptypes/lib/makePropTypesAst.js:14:22)
at Module._compile (module.js:434:26)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require …
```

Minor fixes

---

README.md
src/__test__/fixtures/children.input.js
src/__test__/fixtures/children.output.js
src/__test__/fixtures/import-object.input.js
src/__test__/fixtures/stateless-arrow.input.js
src/__test__/fixtures/stateless-arrow.output.js
src/__test__/fixtures/stateless-inline-defaults.input.js
src/__test__/fixtures/stateless-inline-defaults.output.js
src/__test__/fixtures/stateless-inline.input.js
src/__test__/fixtures/stateless-inline.output.js
src/__test__/fixtures/stateless-without-jsx.input.js
src/__test__/fixtures/stateless-without-jsx.output.js
src/__test__/fixtures/stateless.input.js
src/__test__/fixtures/stateless.output.js
src/convertToPropTypes.js
src/index.js

NOTE: This pull requests is build on top of https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/30 (let us get that merged before this)
I'm addressing two issues:
- solves #11 (support different kinds of functional components)
- solves #9 (stop depending on type definition name ending with Props, but actual look at the variable reference)
@brigand please have a look

Functional components

---

src/__test__/fixtures/stateless.input.js
src/__test__/fixtures/stateless.output.js
src/convertToPropTypes.js

Flow allows you to have union types with `null` as an element. Currently the plugin does not handle this correctly but crashes with:
`Invalid type supplied, this is a bug in babel-plugin-flow-react-proptypes, typeof is undefined with value undefined`.
This pull request should fix it. Please review @brigand

Better handling of UnionTypeAnnotation containing null

---

src/__test__/fixtures/tupletype.input.js
src/__test__/fixtures/tupletype.output.js
src/convertToPropTypes.js

Currently any code using flow tuple types like `[string, Object]` will crash the plugin.
As PropTypes does not support tuples this just introduces basic handling with `PropTypes.arrayOf(PropTypes.any).isRequired`

Basic support for TupleTypeAnnotation

---

src/__test__/fixtures/class-inline-props.input.js
src/__test__/fixtures/class-inline-props.output.js
src/index.js

This solves #35 where type annotation given directly in props for a subclass crashes the plugin.
It reuses the same logic from functional components, so using external types now also works.

Reuse typeannotation logic to fix bug with inline props (solves #35)

---

src/__test__/fixtures/stateless-exports.input.js
src/__test__/fixtures/stateless-exports.output.js
src/index.js

When functional components are declared and exported in the same statement we currently crash. This should fix it.
```javascript
export const C = ({ message } : {
message : string
}) => {
return <div />;
};
```
Fixes https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/35
Please review @brigand

Handle functional components export + declaration

---

src/__test__/fixtures/stateless-arrow-body-without-jsx.input.js
src/__test__/fixtures/stateless-arrow-body-without-jsx.output.js
src/__test__/fixtures/stateless-arrow-body.input.js
src/__test__/fixtures/stateless-arrow-body.output.js
src/index.js

At my company we have many stateless functional components without
BlockStatement as body. Like this:
```js
type Props = { x: string }
const Foo = (props: Props) => <div>{props.x}</div>;
export default Foo;
```
This patch checks the body for JSX and React.createElement, if the body
is a block statement it behaves as before.

Arrowfunctions without body as BlockStatement

---

src/__test__/fixtures/object-props.input.js
src/__test__/fixtures/object-props.output.js
src/convertToPropTypes.js
src/index.js

Right now, this example:
```
const MyComponent = (props: Object) => <div />;
```
Results in:
```
Error: index.js: Did not find type annotation for reference Object
at getPropsForTypeAnnotation (C:\Projects\test\node_modules\babel-plugin-flow-react-proptypes\lib\index.js:38:13)
at getFunctionalComponentTypeProps (C:\Projects\test\node_modules\babel-plugin-flow-react-proptypes\lib\index.js:59:10)
at functionVisitor (C:\Projects\test\node_modules\babel-plugin-flow-react-proptypes\lib\index.js:138:17)
at PluginPass.ArrowFunctionExpression (C:\Projects\test\node_modules\babel-plugin-flow-react-proptypes\lib\index.js:198:16)
at newFn (C:\Projects\test\node_modules\babel-traverse\lib\visitors.js:276:21)
at NodePath._call (C:\Projects\test\node_modules\babel-traverse\lib\path\context.js:76:18)
at …
```

Fixed crash when props are annotated as Object

---

package.json

I also ran into #50, where flow was warning for files inside this module. I noticed that source code and tests were being included in the published npm package, so I took a stab at fixing (or working around, depending on whether that's actually a bug in flow itself) it by including only the compiled source in the published package. Without the uncompiled source and tests, the npm package is smaller, and flow has nothing to complain about. I should note that this approach will only work as long as the source and tests don't need to be in the bundle. Typically they aren't included, but perhaps there's a use case I'm not seeing that would require them.
```sh
$ npm run build
> babel-plugin-flow-react-proptypes@0.17.2 build ~/code/brigand/babel-plugin-flow-react-proptypes
> babel src/ …
```

Use package.json files field

---

src/__tests__/__snapshots__/export-object-test.js.snap
src/__tests__/__snapshots__/export-type-and-component-test.js.snap
src/__tests__/__snapshots__/import-and-loops-test.js.snap
src/__tests__/__snapshots__/typeof-test.js.snap
src/index.js

Object.defineProperty takes a descriptor not a value. Value was always undefined and defaulting to any type when the import was processed.

Properly handle exporting named types

---

src/index.js

Required to work with React Native as the packager applies the application's babelrc to node_modules (and breaks in many and fun ways on React Native's sources when using this plugin).
Fixes #62 #53

Suppress transform of any file in node_modules

---

src/index.js

@brigand @chrisy-lili This adds an option to disable transforming node modules rather than making this a hard decision.
The default is to transform node modules.

Add a babel option ignoreNodeModules to control transform on node modules

---

CHANGELOG.md
src/__tests__/__snapshots__/class-inline-props-test.js.snap
src/__tests__/__snapshots__/import-non-relative.js.snap
src/__tests__/__snapshots__/import-object-test.js.snap
src/__tests__/__snapshots__/intersection-complex-example.js.snap
src/__tests__/__snapshots__/intersection-deeply-nested.js.snap
src/__tests__/__snapshots__/intersection-inline-with-exported-and-nested-imported-type.js.snap
src/__tests__/import-object-test.js
src/makePropTypesAst.js

I just noticed this was broken while working on #92. The isRequired flag was never set on imported types.
This PR includes #92; so perhaps review that one first. I'll be happy to rebase, but I do require most changes from that PR here.
See e167278fb15835f41b986aebc80d62a292e9219a and newer.

Fix required for imported types

---

.travis.yml
README.md
package.json

This PR adds a coverage badge to README.md via the coveralls.io service.
I can't properly test the travis integration. My impression is that it should work out of the box once the repo owner creates an account on coveralls.io and enables the correct repository.
The npm command itself works fine, I tried it: https://coveralls.io/github/mhaas/babel-plugin-flow-react-proptypes

Enable code coverage & coveralls badge

---

CHANGELOG.md
src/__tests__/__snapshots__/test-issue-66.js.snap
src/__tests__/test-issue-66.js
src/index.js

Any function containing a react component is considered a functional
React component by isFunctionalReactComponent().
This leads to false positives for functions which just use or generate
instances of React components. These factory functions do not
follow the general contract of react components. In particular, the
first argument to the function may not be props.
It is hard to detect these cases in isFunctionalReactComponent. Instead,
we relax the sanity check in getPropsForTypeAnnotation: if a typeAnnotation
exists but does not have the type we expect, we do not fail hard.
We just don't generate proptypes.
Not sure if this is the best way to go about this, but it's a start.

Fix issue #66

---

src/__tests__/__snapshots__/object-type-spread-exact.js.snap
src/__tests__/__snapshots__/object-type-spread-simple.js.snap
src/__tests__/object-type-spread-exact.js
src/__tests__/object-type-spread-simple.js
src/convertToPropTypes.js
src/util.js

Closes #103 
Object type spread was introduced in [Flow 0.42.0](https://github.com/facebook/flow/releases/tag/v0.42.0)
_Documentation_ is not yet published, but the [behavior is documented here](https://github.com/facebook/flow/issues/3534#issuecomment-287580240) and this is referenced in the implementation, as use without `$Exact` is odd - it makes all prop values from the spread optional. 
I have mirrored flow behavior, though I expect the [default behavior may change](https://github.com/facebook/flow/issues/3214).  This too is commented in code so we have some sanity to check and change it in the future.
This is on the `babel-7` branch, but it's quite possible this change could be cherry picked back to the `master`.

Implement object type spread

---

src/__tests__/__snapshots__/export-non-object-types-test.js.snap
src/__tests__/__snapshots__/export-string-type.js.snap
src/__tests__/__snapshots__/export-union-type.js.snap
src/__tests__/__snapshots__/instance-of-object-properties.js.snap
src/__tests__/__snapshots__/render-imported-non-shape-types-generate-warnings.js.snap
src/__tests__/__snapshots__/union-types-and-contants.js.snap
src/__tests__/export-string-type.js
src/__tests__/render-imported-non-shape-types-generate-warnings.js
src/makePropTypesAst.js

This worked for anything object-ish (shape, raw, runtime-merge), but not for strings etc.

Mark exported types as required

---

.babelrc
package.json
src/__tests__/__snapshots__/basic-test.js.snap
src/__tests__/__snapshots__/export-exact-object-type.js.snap
src/__tests__/__snapshots__/export-intersection-two-exported-object-type-mixed-literal-type-alias.js.snap
src/__tests__/__snapshots__/export-intersection-type.js.snap
src/__tests__/__snapshots__/export-non-object-types-test.js.snap
src/__tests__/__snapshots__/export-object-test.js.snap
src/__tests__/__snapshots__/export-string-type.js.snap
src/__tests__/__snapshots__/export-type-and-component-test.js.snap
src/__tests__/__snapshots__/export-union-type.js.snap
src/__tests__/__snapshots__/import-and-loops-test.js.snap
src/__tests__/__snapshots__/instance-of-object-properties.js.snap
src/__tests__/__snapshots__/intersection-complex-example.js.snap
src/__tests__/__snapshots__/intersection-export-test.js.snap
src/__tests__/__snapshots__/intersection-inline-with-exported-and-nested-imported-type.js.snap
src/__tests__/__snapshots__/intersection-inline-with-exported-type.js.snap
src/__tests__/__snapshots__/intersection-nested-complex-example.js.snap
src/__tests__/__snapshots__/intersection-two-exported-object-type-literals.js.snap
src/__tests__/__snapshots__/intersection-two-exported-object-type-mixed-literal-type-alias.js.snap
src/__tests__/__snapshots__/string-literal-property.js.snap
src/__tests__/__snapshots__/typeof-test.js.snap
src/__tests__/__snapshots__/union-objects-exact.js.snap
src/__tests__/__snapshots__/union-types-and-contants.js.snap
src/index.js
src/makePropTypesAst.js
yarn.lock

Solves #120 
As it were, if you added `export` to `type Props` it would generate double the code, which we found could become sizable when using with props heavy components.
This change will instead declare a var and reuse such as:
```javascript
var babelPluginFlowReactPropTypes_proptype_Props = { /* ... */ }; 
TextField.propTypes = babelPluginFlowReactPropTypes_proptype_Props;
if (typeof exports !== 'undefined') Object.defineProperty(exports, 'babelPluginFlowReactPropTypes_proptype_Props',   
value: babelPluginFlowReactPropTypes_proptype_Props,
configurable: true
});
```

Prevent export duplication

---

README.md
src/__tests__/__snapshots__/omitRuntimeTypeExport-test.js.snap
src/__tests__/omitRuntimeTypeExport-test.js
src/index.js

Solves #122 
I added a section to the readme that hopefully clarifies intent and use.
/cc @oliviertassinari

Feature: add optional `omitRuntimeTypeExport` to optimize production bundle size

---

src/__tests__/__snapshots__/basic-test.js.snap
src/__tests__/__snapshots__/export-exact-object-type.js.snap
src/__tests__/__snapshots__/export-intersection-two-exported-object-type-mixed-literal-type-alias.js.snap
src/__tests__/__snapshots__/export-intersection-type.js.snap
src/__tests__/__snapshots__/export-non-object-types-test.js.snap
src/__tests__/__snapshots__/export-object-test.js.snap
src/__tests__/__snapshots__/export-string-type.js.snap
src/__tests__/__snapshots__/export-type-and-component-test.js.snap
src/__tests__/__snapshots__/export-union-type.js.snap
src/__tests__/__snapshots__/import-and-loops-test.js.snap
src/__tests__/__snapshots__/instance-of-object-properties.js.snap
src/__tests__/__snapshots__/intersection-complex-example.js.snap
src/__tests__/__snapshots__/intersection-export-test.js.snap
src/__tests__/__snapshots__/intersection-inline-with-exported-and-nested-imported-type.js.snap
src/__tests__/__snapshots__/intersection-inline-with-exported-type.js.snap
src/__tests__/__snapshots__/intersection-nested-complex-example.js.snap
src/__tests__/__snapshots__/intersection-two-exported-object-type-literals.js.snap
src/__tests__/__snapshots__/intersection-two-exported-object-type-mixed-literal-type-alias.js.snap
src/__tests__/__snapshots__/string-literal-property.js.snap
src/__tests__/__snapshots__/typeof-test.js.snap
src/__tests__/__snapshots__/union-objects-exact.js.snap
src/__tests__/__snapshots__/union-types-and-contants.js.snap
src/index.js

Given:
`src/colors.js`:
```
// @flow
export const colors = {
primary: 'primary',
secondary: 'secondary',
error: 'error',
};
export type Color = 'primary' | 'secondary' | 'error';
```
and `index.js`:
```
export * from './colors';
```
Since the generated `babelPluginFlowReactPropTypes_proptype_Color` is not enumerable under `exports`. It will not be exposed by the wildcard export in index.js which babel transpiles to:
```
var _colors = require('./colors');
Object.keys(_colors).forEach(function (key) {
if (key === "default" || key === "__esModule") return;
Object.defineProperty(exports, key, {
enumerable: true,
get: function get() {
return _colors[key];
}
});
});
```
That is `Object.keys(_colors)` only contains `colors` and not `babelPluginFlowReactPropTypes_proptype_Color`
This PR adds the …

make exported proptypes enumerable

---

src/__tests__/__snapshots__/basic-test.js.snap
src/__tests__/__snapshots__/class-and-function-test.js.snap
src/__tests__/__snapshots__/flow-53-generic-test.js.snap
src/__tests__/__snapshots__/function-with-existential-type-test.js.snap
src/__tests__/__snapshots__/intersection-test.js.snap
src/__tests__/__snapshots__/optional-any-test.js.snap
src/__tests__/__snapshots__/stateless-inline-test.js.snap
src/__tests__/__snapshots__/stateless-test.js.snap
src/__tests__/__snapshots__/tupletype-test.js.snap
src/__tests__/__snapshots__/typeof-test.js.snap
src/__tests__/optional-any-test.js
src/makePropTypesAst.js

Fixes the following scenario:
```
type Props = {
foo?: any,
}
const MyComp = (props: Props) => <div />
```
Outputs:
```
MyComp.propTypes = {
foo: require('prop-types').any,
}
```
Fixes #142.
@brigand Does this seem right to you?

fix: optional any types

---

src/__tests__/__snapshots__/context-component-no-props-test.js.snap
src/__tests__/__snapshots__/context-component-test.js.snap
src/__tests__/__snapshots__/context-parametrized-component-test.js.snap
src/__tests__/__snapshots__/context-stateless-arrow-test.js.snap
src/__tests__/context-component-no-props-test.js
src/__tests__/context-component-test.js
src/__tests__/context-parametrized-component-test.js
src/__tests__/context-stateless-arrow-test.js
src/index.js

This PR proposes `contextTypes` generation from Flow annotations.
Resolves #63 
Supported & tested use cases:
* Stateless functional component
* `React.Component` with `context` as an attribute

Add context types

---

src/__tests__/__snapshots__/exists-type.js.snap
src/__tests__/exists-type.js
src/convertToPropTypes.js
yarn.lock

The only problem I got was that ```ExistentialTypeParam``` has been renamed to ```ExistsTypeAnnotation```
```NumericLiteralTypeAnnotation``` to ```NumberLiteralTypeAnnotation``` and that the value of a ```NullLiteralTypeAnnotation``` no longer contains any value (before it was true)
These changes allow this plugin to be run with babel7 and babel6.

Babel7 compat

---

README.md
a.js
package.json
scripts/runOnFile
src/__tests__/__snapshots__/dead-code-exports-test.js.snap
src/__tests__/__snapshots__/dead-code-string-test.js.snap
src/__tests__/__snapshots__/dead-code-true-test.js.snap
src/__tests__/dead-code-exports-test.js
src/__tests__/dead-code-string-test.js
src/__tests__/dead-code-true-test.js
src/index.js
yarn.lock

Partially resolves #70 #154
Done:
- added `deadCode` config option (see readme)
- dce for the propTypes object
- dce for exported types (`export type Foo =`)
Remaining (PRs welcome)
- dce for imported types (`import type {Foo} from './Foo`)
- dce for the actual 'propTypes' property, both with the default assignment at end of file, and the the `useStatic` option (currently `propTypes=null` after minify)
If anyone picks up these tasks, see `src/__tests__/dead-code-true-test.js` for an example of a test that uses uglify to test the minified output.
cc @sohkai

Dead code part 1

---

src/index.js

Overview
--------
While upgrading this plugin to v14 in a codebase that uses Babel v7 (beta), we encountered this error:
```
Error: Unknown substitution "NAME" given
at /home/spainhower/repos/hz-wl-webapps/node_modules/@babel/template/lib/populate.js:21:15
at Array.forEach (<anonymous>)
at populatePlaceholders (/home/spainhower/repos/hz-wl-webapps/node_modules/@babel/template/lib/populate.js:19:31)
at /home/spainhower/repos/hz-wl-webapps/node_modules/@babel/template/lib/string.js:20:51
at Object.named (/home/spainhower/repos/hz-wl-webapps/node_modules/@babel/template/lib/builder.js:83:14)
```
It appears that babel v7 templates are more strict regarding the substitutions with which they are called.  All provided substitutions must be used in the template.  This PR just tightens up those …

fix(templates): Stricter substitution usage

---

src/index.js

Set name variable to path.node.id.name when path.type matches ClassDeclaration or ClassExpression
We were seeing the following error because `name` is undefined when `path.type` is `ClassDeclaration` or `ClassExpression`, and `name` is a required field for the babel-types identifier call. 
https://github.com/brigand/babel-plugin-flow-react-proptypes/blob/master/src/index.js#L218
https://github.com/babel/babel/tree/master/packages/babel-types#identifier
```sh
TypeError: Property name expected type of string but got null
at validate (/home/circleci/repo/node_modules/@babel/types/lib/definitions/utils.js:175:13)
at Object.validate (/home/circleci/repo/node_modules/@babel/types/lib/definitions/utils.js:191:10)
at validate (/home/circleci/repo/node_modules/@babel/types/lib/validators/validate.j …
```

fix(annotate) Set name for path Class types

---

src/__tests__/__snapshots__/real2-test.js.snap
src/__tests__/real2-test.js
src/index.js

Basically this includes a file from my work that crashed the plugin.
Instead of crashing we now ignore a property that wasn't found.

"fix" for Generics on functions

---

src/__tests__/__snapshots__/import-imported-clash.js.snap
src/__tests__/import-imported-clash.js
src/index.js

This fixes #176. Got suddenly sleepy a lot and couldn't get my mind into the game so variable naming and code structure probably could be a little bit better, but unfortunately I have to get to other things right now. 
I suspect (didnt check) that this issue also affects other cases:
- cjs style - I havent touched that branch of the code
- `export type { Foo as Bar } from './foo'`
I can work on those, but certainly not before the weekend and also not sure how much time I will have then, so feel free to pick up this if you want from where I left - if you have any comments regarding changes in this PR I will find some time to adjust it based on your suggestions.

Fixed case with imported types with different local name

---

src/__tests__/__snapshots__/real3-test.js.snap
src/__tests__/real3-test.js
src/makePropTypesAst.js

In Babel7 the identifier has to be cloned to get the import Name prefix.
For the intersection babel7 would generate the following code:
```js
var bpfrpt_proptype_JobViewImpression = Object.assign({}, _JLCommon.bpfrpt_proptype_Job === _propTypes2.default.any ? {} : bpfrpt_proptype_Job, {
resultId: _propTypes2.default.string,
listIndex: _propTypes2.default.number.isRequired,
searchType: _propTypes2.default.string,
viewSource: _propTypes2.default.string
});
```
As you can see the```_JLCommon``` is missing on the second ```bpfrpt_proptype_Job``` this is because both ```bpfrpt_proptype_Job```were the same node before. Now I clone it.
Babel7 no longer adjusts both identifier if it was the same node.

[Babel7] Compat for intersection & imported types

---

src/__tests__/__snapshots__/objectof-test.js.snap
src/__tests__/__snapshots__/real4-test.js.snap
src/__tests__/objectof-mixed-indexers-named-test.js
src/__tests__/objectof-multiple-indexers-test.js
src/__tests__/objectof-test.js
src/convertToPropTypes.js
src/makePropTypesAst.js

Summary:
This commit adds support for types like `{[name: string]: number}`,
which describes an object with arbitrary keys and numeric values. The
corresponding PropType is `PropTypes.objectOf(PropTypes.number)`.
Two variants are rejected outright. First, Flow does not support types
with multiple indexers: `{[a: string]: number, [b: string]: number}` is
not a valid type expression. You can verify this by pasting the
following into the Flow playground:
```
type X = {[a: string]: number, [b: string]: number};
```
This gives the error:
```
1: type X = {[a: string]: number, [b: string]: number};
^ Multiple indexers are not supported.
```
It therefore seems reasonable to reject any such type expressions that
make it into the AST.
On the other hand, Flow _does_ support mixing indexers and named …

Add support for indexed objects (`objectOf`)

---

README.md
src/__tests__/__snapshots__/array-shorthand-test.js.snap
src/__tests__/__snapshots__/arrayof-objectof-required-test.js.snap
src/__tests__/__snapshots__/basic-test.js.snap
src/__tests__/__snapshots__/children-test.js.snap
src/__tests__/__snapshots__/generic-array.js.snap
src/__tests__/__snapshots__/import-and-loops-test.js.snap
src/__tests__/__snapshots__/objectof-test.js.snap
src/__tests__/__snapshots__/real4-test.js.snap
src/__tests__/__snapshots__/stateless-inline-test.js.snap
src/__tests__/__snapshots__/stateless-test.js.snap
src/__tests__/arrayof-objectof-required-test.js
src/convertToPropTypes.js

Summary:
Fixes #183; see rationale there.
Test Plan:
The code change to `convertToPropTypes` is sufficient to fix the
`generic-array` and `objectof` tests, including the test modified in
this commit:
yarn test objectof generic-array
Obviously, this is a wide-reaching change, so several other snapshots
were invalidated. I generated them, and manually inspected the results
to ensure that the changes are correct. They are, as far as I can tell;
the arrays of external types are harder to read, but by comparison with
surrounding code they seem okay to me.
wchargin-branch: arrayof-objectof-elements-required

Allow `arrayOf`/`objectOf` elements to be required

---

src/__tests__/__snapshots__/import-component-type-from-react-test.js.snap
src/__tests__/__snapshots__/import-non-relative.js.snap
src/__tests__/__snapshots__/real3-test.js.snap
src/__tests__/__snapshots__/real4-test.js.snap
src/__tests__/__snapshots__/top-level-import-test.js.snap
src/__tests__/real4-test.js
src/index.js

This ignores type imports when the path looks like a node_modules import (e.g. `'lodash'`). See #181
@marudor you added some tests recently that use non-relative imports. Would this break your stuff?
From what I can tell, this solves exactly one case: you're importing a flow type from a node_modules package, where the resolved file is an ESM, but wasn't processed by this plugin.

No import node modules 181

---

src/__tests__/__snapshots__/import-non-relative.js.snap
src/__tests__/import-non-relative.js
src/index.js

Updates the node_modules regex to also catch namespaces, e.g. `@namespace/foo`.

Ignore namespaced node_modules

---

src/__tests__/__snapshots__/opaque-type-alias-test.js.snap
src/__tests__/opaque-type-alias-test.js
src/convertToPropTypes.js
src/index.js

This change supports using opaque type aliases as if they were regular
types, i.e. the generated propTypes code is based on the underlying
type information.

Add support for opaque type aliases

---

src/__tests__/__snapshots__/imported-spread-test.js.snap
src/__tests__/imported-spread-test.js
src/convertToPropTypes.js

Minimal example, where we import a type, and then try to spread it:
```js
import { type Foo } from './Foo';
export type Something = {
...Foo,
}
```
This change causes it not to error, however we just eliminate the spread for now.
To actually support this, we'd need to wrap the spread type in a custom fake propTypes function, like this:
```js
const bpfrpt_proptype_Something = {
__made_up_prop: (...args) => {
// apply `bpfrpt_proptype_Foo` to the props object
}
}
```
If anyone wants to try implementing this and has time to test it well, that'd be great.

fixes error for spread on imported type, resolves #204
